name: flutter_telegram_miniapp
description: "A Flutter package providing easy access to the Telegram Mini Apps API, enabling you to build interactive experiences within Telegram."
version: 0.0.10
homepage: https://github.com/KirillRedactor/telegram_miniapp
issue_tracker: https://github.com/KirillRedactor/telegram_miniapp/issues


environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0